config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :photos, only: [:new, :create, :update, :edit, :destroy]
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :bookings, only: [:index, :create, :update, :destroy]
  get '/listings', to: 'flats#listings_index', as: :listings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user

  validates :state, presence: true
  validates :total_price, presence: true
  validate :end_after_start
  validates :start_date, :end_date, :presence => true
  validate :trip_before_today

  private

  def end_after_start
    return if end_date.blank? || start_date.blank?

    if end_date <= start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def trip_before_today
    return if end_date.blank? || start_date.blank?
    if Date.today > start_date
      errors.add(:start_date, "must be at least today")
    end
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :location, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :description, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch
    pg_search_scope :global_search,
      against: [ :name, :description, :location ],
      using: {
        tsearch: { prefix: true }
    }

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :flat
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: { with: /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\Z/i }, presence: true, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end

  after_action :verify_authorized, except: [:index, :listings_index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :listings_index], unless: :skip_pundit?

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :update, :destroy]

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      @flat = @booking.flat
      render "flats/show"
    end
  end

  def update
    authorize @booking
    @booking.update(booking_params)
    redirect_to listings_path
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:flat_id, :start_date, :end_date, :total_price, :state)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_flat, only:  [:show, :edit, :update, :destroy]

  def index
    @flats = policy_scope(Flat).order(created_at: :desc)
    if params[:query] && params[:query] != ""
      @flats = @flats.global_search(params[:query]) # .where.not(latitude: nil, longitude: nil)
    end

    if params["min-capacity"] && params["min-capacity"] != ""
      @flats = @flats.where("capacity >= ?", params['min-capacity'])
    end

    @markers = @flats.map do |flat|
      {
        lng: flat.longitude,
        lat: flat.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { flat: flat })
      }
    end
  end

  def show
    @booking = Booking.new
    authorize @flat
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def edit
    authorize @flat
  end

  def update
    authorize @flat
    if @flat.update(flat_params)
      redirect_to @flat
    else
      render :edit
    end
  end

  def create
    @flat = Flat.new(flat_params)
    authorize @flat
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def destroy
    authorize @flat
    @flat.destroy
    redirect_to flats_path
  end

  def listings_index
    @flats = policy_scope(Flat).order(created_at: :desc).where(user: current_user)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :location, :price_per_night, :description, :capacity)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_flat, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_photo, only: [:edit, :update, :destroy]

  def new
    @photo = Photo.new
    authorize @photo
  end

  def create
    @photo = Photo.new(photo_params)
    authorize @photo
    @photo.flat = @flat
    if @photo.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    authorize @photo
  end

  def update
    authorize @photo
    if @photo.update(photo_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    authorize @photo
    @photo.destroy
    redirect_to flat_path(@flat)
  end

  private

  def find_photo
    @photo = Photo.find(params[:id])
  end

  def find_flat
    @flat = Flat.find(params[:flat_id])
  end

  def photo_params
    params.require(:photo).permit(:photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    redirect_to edit_user_path(current_user)
    # @user = current_user
    # authorize @user
    # format.html { render 'users/edit' }
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    authorize @user
    @user.update_without_password(user_params)
    redirect_to edit_user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:photo, :first_name, :last_name, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="page-content">
  <div class="index-flex">
    <div class="flats-list">
      <h1 class="main-title text-center">All Bookings</h1>
      <div class="row">
          <% @bookings.each do |booking| %>
            <div class="col-sm-6 col-md-4">
              <div class="flats-card booking-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= booking.flat.photos.first ? booking.flat.photos.first.photo : image_path('apt-beton.jpg') %>');">
                <div class="card-content">
                  <p class="card-location"><%= booking.flat.location %></p>
                  <h3 class="card-name"><%= booking.flat.name %></h3>
                </div>
                <div class="card-price">
                  <h3> €<%= booking.total_price %></h3>
                </div>
                <div class="absolute">
                  <p class="booking-dates"><%= booking.start_date.strftime("%b %d %Y") %> - <%= booking.end_date.strftime("%b %d %Y") %></p>
                </div>
                <%= link_to "", flat_path(booking.flat), class: "card-link" %>
                <div class="booking-state-div">
                  <p class=<%= booking.state %>>
                    <%= booking.state.capitalize %>
                  </p>
                </div>
                  <div class="booking-action trash">
                    <%= link_to booking_path(booking), method: :delete, data: { confirm: 'Are you certain you want to delete this?'} do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  </div>


              </div>
            </div>
          <% end %>
      </div>
    </div>
</div>
</div>

app/views/flats/_form.html.erb
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <%= simple_form_for(flat) do |f| %>
        <%= f.input :name %>
        <%= f.input :location %>
        <%= f.input :capacity %>
        <%= f.input :price_per_night %>
        <%= f.input :description %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>

app/views/flats/_infowindow.html.erb
<div class="flats-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= flat.photos.first ? flat.photos.first.photo : image_path('apt-beton.jpg') %>');">
  <div class="card-content">
    <p class="card-location"><%= flat.location %></p>
    <h3 class="card-name"><%= flat.name %></h3>
  </div>
  <div class="card-price">
    <h3> €<%= flat.price_per_night %></h3>
    <h3><i class="fas fa-user"></i>    <%= flat.capacity %></h3>
  </div>
  <%= link_to "", flat_path(flat), class: "card-link" %>
</div>

app/views/flats/edit.html.erb
<div class="container" >
  <h1 class="text-center"> Edit Your Flat! </h1>
    <%= render 'form', flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="page-content">
  <div class="index-flex">
    <div class="flats-list">
      <h1 class="main-title text-center">All Flats</h1>

      <div class="row">
        <% @flats.each do |flat| %>
          <div class="col-md-6 col-lg-4">
            <div class="flats-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= flat.photos.first ? flat.photos.first.photo : image_path('apt-beton.jpg') %>');">
              <div class="card-content">
                <p class="card-location"><%= flat.location %></p>
                <h3 class="card-name"><%= flat.name %></h3>
              </div>
              <div class="card-price">
                <h3>€<%= flat.price_per_night %></h3>
                <h3><i class="fas fa-user"></i>    <%= flat.capacity %></h3>
              </div>
              <%= link_to "", flat_path(flat), class: "card-link" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
<!-- Gmaps JavaScript -->
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzER7O10ZOUp7FloJzMe2r8X1GIQhgt7Q&callback=initMap">
</script>

app/views/flats/listings_index.html.erb
<div class="page-content">
  <div class="container">
    <div class="index-flex">
      <div class="flats-list">
        <h1 class="main-title text-center">All Listings</h1>
          <div class="row">
            <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">

              <ul class="bookings-list">
                <% @flats.each do |flat| %>
                  <% flat.bookings.each do |booking| %>
                      <li class="booking">
                        <%= image_tag "apt-beton.jpg", class: "listing-avatar" %>
                        <div class="listing-sender">
                          <h2><%= booking.user.full_name %></h2>
                        </div>
                        <div class="listing-message">
                          <h2><%= booking.flat.name %></h2>
                          <h3><%= booking.start_date.strftime("%b %d %Y") %> - <%= booking.end_date.strftime("%b %d %Y") %></h3>
                        </div>
                        <% if booking.state == "pending" %>
                          <div class="listing-actions">
                            <%= simple_form_for(booking) do |f| %>
                              <%= f.input :state, as: :hidden, input_html: {value: 'accepted'} %>
                              <%= f.submit "Accept", class: "btn btn-success" %>
                            <% end %>
                            <%= simple_form_for(booking) do |f| %>
                              <%= f.input :state, as: :hidden, input_html: {value: 'rejected'} %>
                              <%= f.submit "Reject", class: "btn btn-danger" %>
                            <% end %>
                          </div>
                        <% end %>
                        <div class="listing-status">
                          <h2 class=<%= booking.state %>>
                            <%= booking.state.capitalize %>
                          </h2>
                          <h3 class="listing-price"><%= booking.total_price %>€</h3>
                        </div>
                      </li>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>



        </div>
      </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container" >
  <h1 class="text-center"> List Your Flat! </h1>
    <%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div>
  <div id="room">

    <!-- picture banner starts here -->

    <div class="grid pictures-banner">
      <% if @flat.photos.first %>
        <div id="picture1" class="apt-pic" style="background-image: url('<%= cl_image_path(@flat.photos.first.photo) %>')">
          <% if policy(@flat).edit? %>
            <div class="edit-pen">
              <%= link_to edit_flat_photo_path(@flat, @flat.photos.first) do %>
                <i class="far fa-edit"></i>
              <% end %>
            </div>
            <div class="trash">
              <%= link_to flat_photo_path(@flat, @flat.photos.first), method: :delete, data: { confirm: 'Are you certain you want to delete this?'} do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      <% else %>
        <div id="picture1" class="add-photo">
          <% if policy(@flat).edit? %>
            <p>+</p>
            <%= link_to "", new_flat_photo_path(@flat), class: "add-photo-link" %>
          <% end %>
        </div>
      <% end %>
      <% counter = 1 %>
      <% 4.times do %>
        <% if @flat.photos[counter] %>
          <div class="apt-pic" style="background-image: url('<%= cl_image_path(@flat.photos[counter].photo) %>')">
            <% if policy(@flat).edit? %>
              <div class="edit-pen">
                <%= link_to edit_flat_photo_path(@flat, @flat.photos[counter]) do %>
                  <i class="far fa-edit"></i>
                <% end %>
              </div>
              <div class="trash">
                <%= link_to flat_photo_path(@flat, @flat.photos[counter]), method: :delete, data: { confirm: 'Are you certain you want to delete this?'} do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="add-photo">
            <% if policy(@flat).edit? %>
              <p>+</p>
              <%= link_to "", new_flat_photo_path(@flat), class: "add-photo-link" %>
            <% end %>
          </div>
        <% end %>
        <% counter += 1 %>
      <% end %>
    </div>

    <!-- description starts here -->

    <div class="row">
      <div class="container">
        <div class="flat-description">
          <div class="col-sm-8">
            <div class="show-title">
              <h1> <%= @flat.name %> </h1>
              <% if policy(@flat).edit? %>
                <div class="show-title-functions">
                  <div class="edit-pen">
                    <%= link_to edit_flat_path(@flat) do %>
                      <i class="far fa-edit"></i>
                    <% end %>
                  </div>
                  <div class="trash">
                    <%= link_to flat_path(@flat), method: :delete, data: { confirm: 'Are you certain you want to delete this?'} do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
            <h2> <%= @flat.location %> </h2>
            <h3><i class="fas fa-user"></i>    <%= @flat.capacity %></h3>
            <p> <%= @flat.description %> </p>
          </div>

          <!-- booking box here -->
          <div class="col-sm-4">
            <div class="booking-box">
              <div class="price_night">
                  <p> Price per night: </p>
                  <h3 class="price-per-night"><%= @flat.price_per_night %>€</h3>
              </div>

              <div>
                <p>When do you want to travel?</p>
                <% if @booking.errors.any? %>
                  <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <%= @booking.errors.full_messages.join(",") %>
                  </div>
                </div>
                <% end %>
                <%= simple_form_for(@booking) do |f| %>
                  <%= f.input :start_date, as: :date, html5: true %>
                  <%= f.input :end_date, as: :date, html5: true %>
                  <%= f.input :flat_id, as: :hidden, input_html: { value: @flat.id } %>
                  <%= f.input :total_price, as: :hidden, input_html: { value: @flat.price_per_night }%>
                  <div class="price_total hidden">
                    <p> Total price: </p>
                    <h3 id="total-price">€</h3>
                  </div>
                  <div class="price_total_none hidden">
                    <p> Please set your travel dates to display total price </p>
                  </div>

                  <%= f.submit "Request Booking", class: "btn btn-danger" %>
                <% end %>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pokebnb</title>
    <%= favicon_link_tag asset_path('logo-turtle.png') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'devise/shared/flashes' %>
    <%= yield %>


    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.4)), url(<%= image_path('treehouse.jpg') %>)">
  <div class="banner-content">
    <h1 class="text-center">Plan your next adventure</h1>
    <div class="search-form">
      <form action=<%= flats_path %> class="form-inline">
        <div class="flex">
          <input type="text" name="query" id="search-location-home" placeholder="Your destination">
          <input type="number" name="min-capacity" id="search-capacity" class="form-control" placeholder="Guests">
          <input type="submit" class="btn btn-danger search-submit" value="Search">
        </div>
      </form>
    </div>
  </div>
</div>

app/views/photos/_form.html.erb
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
        <%= simple_form_for [@flat, @photo] do |f| %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit class: "btn-blue" %>
      <% end %>
    </div>
  </div>

app/views/photos/edit.html.erb
<div class="container" >
  <h1 class="main-title text-center"> Edit Your Photo! </h1>
    <%= render 'form', photo: @photo %>
</div>

app/views/photos/new.html.erb
<div class="page-content">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
        <h1 class="main-title text-center">Add a new Photo</h1>
          <%= render 'form', photo: @photo %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container" >
  <h1 class="text-center">List Your Flat! </h1>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <%= simple_form_for(flat) do |f| %>
        <%= f.input :name %>
        <%= f.input :location %>
        <%= f.input :price_per_night %>
        <%= f.input :description %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <div class="navbar-wagon-left">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-turtle.png", height: 50 %>
    <% end %>

    <!-- Search field here -->
    <div class="search hidden-xs">
      <form action=<%= flats_path %> class="form-inline">
        <div class="flex">
          <input type="text" name="query" id="search-location-nav" placeholder="Search city..." class="form-control">
          <input type="submit" id="submit" value="Search" class="btn btn-danger search-submit">
        </div>
      </form>
    </div>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <%= link_to "All Flats", flats_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "New Flat", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <!-- if (condition) do -->
          <% if current_user.photo.blank? %>
            <%= image_tag "https://images.pond5.com/4k-empty-avatar-spinning-icon-footage-072475125_prevstill.jpeg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_path(current_user) do %>
                <i class="fa fa-user"></i> Profile
              <% end %>
            </li>
            <li>
              <%= link_to bookings_path do %>
                <i class="fas fa-book"></i>  Bookings
              <% end %>
            </li>
            <li>
              <%= link_to listings_path do %>
                <i class="fas fa-list"></i>  Listings
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to new_flat_path do %>
              <i class="fas fa-plus-square"></i>  New Flat
            <% end %>
          </li>
          <li>
            <%= link_to flats_path do %>
              <i class="fas fa-home"></i>  All Flats
            <% end %>
          </li>
          <li>
            <%= link_to bookings_path do %>
              <i class="fas fa-book"></i>  Bookings
            <% end %>
          </li>
          <li>
            <%= link_to listings_path do %>
              <i class="fas fa-list"></i>  Listings
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path %></li>
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path %></li>
          <li><%= link_to "All Flats", flats_path %></li>
        <% end %>
      </ul>
    </div>
  </div>


</div>

app/views/users/edit.html.erb
<div class="page-content">
  <div class="index-flex">
    <div class="container flats-list">
      <h1 class="main-title text-center">Profile</h1>
      <div class="row">
       <div class="col-xs-5 col-sm-offset-1">
        <%= simple_form_for(@user) do |f| %>
          <%= f.input :first_name%>
          <%= f.input :last_name%>
          <%= f.submit "Update Name" %>
        <% end %>
        <h3>Email: <%= @user.email %></h3>
       </div>
       <div class="col-xs-5 col-sm-offset-1">
        <%= cl_image_tag @user.photo, height: 300, width: 400, crop: :fill %>
        <%= simple_form_for(@user) do |f| %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "Update Profile Pic" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>